# Generated by Django 4.2.23 on 2025-08-19 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='contact_info',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^\\+?\\d{10,15}$', 'Enter a valid phone number')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(choices=[('hostel', 'Hostel'), ('library', 'Central Library'), ('sports', 'Sports Complex'), ('academic', 'Academic Building'), ('others', 'Others')], max_length=50),
        ),
    ]
