# Generated by Django 4.2.23 on 2025-08-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_item_contact_info_alter_item_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('stationery', 'Stationery'), ('wallets', 'Wallets & Accessories'), ('books', 'Books'), ('id_cards', 'ID Cards'), ('keys', 'Keys'), ('clothing', 'Clothing'), ('others', 'Others')], default='Others', max_length=50),
        ),
    ]
